line-length = 100
indent-width = 4
target-version = "py313"

[lint]
select = ["E", "F", "I", "B"]
ignore = []
unfixable = ["F401"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
